### ISSUE TITLE
Forward auth and login

### ISSUE THREAD

**Issue by daenney** [sebadob/rauthy#1052]
I'm trying to use Rauthy to lock down the Syncthing UI, which doesn't natively support oauth2. My only options are a static credential, or LDAP.

I've got it working with Caddy's `forward_auth` directive, except that I always get an error from Rauthy back:

```json
{"timestamp":1750195474,"error":"Unauthorized","message":"Authorization header missing"}
```

I suppose this makes sense, since my browser doesn't know to add an authorisation header. In most other cases where I've seen this implemented, there's a way to tell the proxy to redirect to the login portal and handle this. I'm not sure if Rauthy can do this, or if I'm holding it wrong?

Configuration wise in Rauthy I have:

```toml
[auth_headers]
enable = true
```

And for Caddy, it looks like:
```caddyfile
sync.example.com {
    forward_auth https://id.example.com {
        header_up Host {upstream_hostport}
        uri /auth/v1/oidc/forward_auth
        copy_headers X-Forwarded-User
    }

    reverse_proxy 127.0.0.1:8384
    tls <redacted>
    encode
```

**Comment by dotsam** [comment]
I don’t believe rauthy currently supports this sort of flow, but as discussed in #989, this could be implemented

**Comment by sebadob** [comment]
> I don’t believe rauthy currently supports this sort of flow

Correct. The `/forward_auth` expects a JWT token in the `Authorization` header. It will validate it will all parts and components included, and will then inject the forward auth headers on success.

Since more and more people seem to need a solution for this, I will add a custom callback endpoint with probably the next release, which can be injected into clients by your reverse proxy.

**Comment by daenney** [comment]
> Since more and more people seem to need a solution for this, I will add a custom callback endpoint with probably the next release, which can be injected into clients by your reverse proxy.

I think your NLnet grant probably put Rauthy on the radar of the selfhostosphere 😄. It's one of the very few OIDC implementations that you don't need a whole external relational DB and a memcached/Redis deployment for, so it's extremely attractive.

But a lot of stuff people may want to self-host are hobby projects by others that don't necessarily include OIDC support.

**Comment by sebadob** [comment]
> It's one of the very few OIDC implementations that you don't need a whole external relational DB and a memcached/Redis deployment for

Yeah that was one of the reasons for me to start this project years ago. Especially for an IdP which rarely has a database bigger than a few MB (for somewhat smaller orgs even), it's just insane to spin up and especially maintain Postgres / mysql.

But, when I do an additional implementation in that regard, I will do it properly with real sessions that you can actually revoke and so on. That's kind of always my problem, that implementations get way bigger than expected in the first place, because I hate doing things in a "that's good enough" manner. I now already started on an implementation and yeah, when you want to do it properly, it's quite a bit of work.

**Comment by sebadob** [comment]
I do have a working example now with all the checks I wanted to have, so it's actually secure and does not have too many footguns like the traditional `/forward_auth`. It can now even check CSRF on it's own without any modifications necessary on the existing app / client side.

I do have an example config for nginx with its `auth_request` module, which can be made a lot more pretty when you use snippets and `include`, but I wanted to keep everything in a single file for the example. I also wanted to create a Traefik example, but I've never used it outside of K8s and its giving me a hard time to even create a simple reverse proxy route from a static file backend. Need to dig a bit deeper into this I guess. I have no idea about Caddy, I've never used it.

I was even able to bind all of this logic to a real Rauthy session, which means you can revoke access at any time, which is super cool and I am not aware of any other implementation, that can do this, but on the other hand, I have not looked at many solutions lately, since I usually don't need this feature.

I can build a nightly image for testing tomorrow, if you would like to give it a try. I tried to design it in a way that you have the most flexibility and compatiblity with all the reverse proxies. Testing "all" of them requires help from others though.

**Comment by daenney** [comment]
I am happy to try and figure out the Caddy bits. If you can post the nginx example that would help a lot in figuring out the Caddy bits, it tends to not be too dissimilar.

**Comment by sebadob** [comment]
I pushed a nightly testing image. This is safe to use on a production DB, it does not bring any DB migrations and you can roll back at any time: `ghcr.io/sebadob/rauthy:0.30.3-20250619-fwd-auth`

 If you could do some testing an your side, that would be really nice. I have no idea why Traefik does not do locally what I want it to, the documentation is lacking a complete example, when you don't want all this "magic auto-discovery stuff" and do a static config, but I will probably do some testing inside K8s with the nightly. 

If you can make it work with a local setup that could be added to the repo for future testing and then Docs later on, that would be really nice. For nginx, I got it working. This is the config I used:

https://github.com/sebadob/rauthy/blob/feat-advanced-forward-auth/assets/nginx/conf.d/default.conf

It contains a bit more proxy optimizations than the bare minimum you need to make it work, but all the proxy config stuff can be outsourced into snippets and included in different locations, when you want to cleanup your bigger prod config.

# How it works

I added 2 new endpoints to Rauthy:

- `/auth/v1/clients/{id}/forward_auth`
- `/auth/v1/clients/{id}/forward_auth/callback`

The `/auth/v1/clients/{id}/forward_auth` is used to process the auth requests. It reads a few different headers that are injected by the proxy:

- X-Forwarded-For / X-Real-Ip
- X-Forwarded-Proto
- X-Forwarded-Host
- X-Forwarded-Method
- X-Forwarded-URI

The additional `X-Original-URI` is a duplicate and only exists currently because it's mentioned in many guides. However, Rauthy accepts either `X-Forwarded-URI` or `X-Original-URL` and checks both of them to provide more compatibility. You can provide any of them.

The `X-Forwarded-Proto` and `X-Forwarded-Host` will be merged into the final `Origin`, that would be provided by the browser if it was a direct request. This is then matched against the `allowed_origin`s configuration for the client to have an additional safety hook in case of proxy misconfiguration or exposing the wrong forward auth on the wrong route. Depending on `X-Forwarded-Method`, Rauthy will do an additional CSRF check. It does 2 of them:

- Check the additional `strict` cookie and match the included, encrypted CSRF token value to the one from the also encrypted session cookie
- Make sure that the `sec-fetch-site` is either `none` or `same-origin`

Usually, one of the methods would already be sufficient. Checking both of them is an additional defense in depth. If you use a somewhat up-to-date browser, this will secure you against CSRF. 

Unlike the already existing `forward_auth`, the new endpoints checks for an encrypted session cookie. This is much more secure, but requires more setup. The session will be bound to the already running Rauthy session, so you can revoke it any time.

The forward auth headers will only be added, if they are enabled. The endpoint works just fine with them being disabled. It will then only authenticate the request and you can skip parsing and forwarding all those response headers to the client, which will make the  config way smaller.

The `danger_cookie_insecure` param will make the cookie insecure for local testing. This makes it possible to test via plain HTTP, which you of course should never set in prod. You have a seoncd param `redirect_state` you can provide to change the
status code, if no session could be found. By default, it returns a `401`, which is why nginx in that case extracts the `location` header and returns it to the user, which will redirect to the `/authorize` page.

To make all of this work with secure cookies, (Rauthy sets `__Host-*` cookies for max security (without the `danger_cookie_insecure`), you need to inject the callback URL into your client app with the reverse proxy. In this example, it's this block:

```
location = /callback {
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;

    proxy_pass http://rauthy/auth/v1/clients/test/forward_auth/callback?$args;
}
```

The callback endpoint only needs 

- X-Forwarded-Proto
- X-Forwarded-Host
- X-Forwarded-For or X-Real-Ip

It will then, depending on the also encrypted `state` param from the `/authorize`, create new session cookies for that injected domain which will be bound to the original Rauthy session created during the login. Afterward, it will redirect to the original URI of the reqeust before the forward auth failed for best UX `X-Original-URI` / `X-Forwarded-URI`.

## Client Config

You can use any client in Rauthy, as long as it meets some config criteria:

- must not have PKCE enabled, because it's an unnecessary overhead when Rauthy does a request against "itself"
- must have at least one allowed origin configured that matches the origin of the location where it will be injected into
- the first configured `redirect_uri` must be absolute (not end with a wildcard `*`) - the redirect to the `/callback` will be created from the first allowed `redirect_uri` automatically to have another safety hook and prevent misuse on proxy level

## nginx

Just for additional reference, this is the complete nginx config when running on localhost:

```
upstream rauthy {
    server localhost:8080;
}

server {
    listen       8000;
    server_name  localhost;

    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    proxy_http_version 1.1;
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;
    client_body_buffer_size 128k;

    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;

    location = /forward_auth {
        internal;

        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Forwarded-Method $request_method;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-URI $request_uri;

        proxy_set_header Content-Length "";
        proxy_set_header Connection "";
        proxy_pass_request_body off;

        # Expects a properly configured client with the id `test`
        #
        # NEVER set `danger_cookie_insecure=true` in production!
        # This is only used for testing purposes!
        #
        # Apart from `danger_cookie_insecure`, you can optionally pass in
        # `redirect_state` which will change the default `401` state if
        # validation failed and nginx should redirect. nginx can handle this
        # dynamically, but it exists for compatibility.
        proxy_pass http://rauthy/auth/v1/clients/test/forward_auth?danger_cookie_insecure=true;
    }

    location = /callback {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;

        proxy_pass http://rauthy/auth/v1/clients/test/forward_auth/callback?$args;
    }

    location /whoami {
        auth_request /forward_auth;
        auth_request_set $redirection_url $upstream_http_location;
        error_page 401 =302 $redirection_url;

        ## Auth Headers Rauthy sends when `auth_headers.enable = true`
        auth_request_set $user $upstream_http_x_forwarded_user;
        auth_request_set $roles $upstream_http_x_forwarded_user_roles;
        auth_request_set $groups $upstream_http_x_forwarded_user_groups;
        auth_request_set $email $upstream_http_x_forwarded_user_email;
        auth_request_set $email_verified $upstream_http_x_forwarded_user_email_verified;
        auth_request_set $family_name $upstream_http_x_forwarded_user_family_name;
        auth_request_set $given_name $upstream_http_x_forwarded_user_given_name;
        auth_request_set $mfa $upstream_http_x_forwarded_user_mfa;

        ## Inject Auth Headers into the request to the client app
        proxy_set_header x-forwarded-user $user;
        proxy_set_header x-forwarded-user-roles $roles;
        proxy_set_header x-forwarded-user-groups $groups;
        proxy_set_header x-forwarded-user-email $email;
        proxy_set_header x-forwarded-user-email-verified $email_verified;
        proxy_set_header x-forwarded-user-family-name $family_name;
        proxy_set_header x-forwarded-user-given-name $given_name;
        proxy_set_header x-forwarded-user-mfa $mfa;

        proxy_pass http://rauthy/auth/v1/whoami;
    }
}
```

And the container started with 

```bash
docker run -it --rm \
    -v ./assets/nginx/conf.d:/etc/nginx/conf.d:ro \
    -v ./assets/nginx/access.log:/var/log/nginx/access.log \
    --network host \
    --name nginx-rauthy-test \
    nginx
```

## Traefik

Even though Traefik for whatever reason does not respect my file provider routes, I am pretty sure the forward auth middleware needs to look like this:

```yaml
      forwardAuth:
        # the id for the properly configured client is `test` in this case
        address: http://localhost:8080/auth/v1/clients/test/forward_auth?redirect_state=302
        trustForwardHeader: true
        authResponseHeaders:
          - x-forwarded-user
          - x-forwarded-user-roles
          - x-forwarded-user-groups
          - x-forwarded-user-email
          - x-forwarded-user-email-verified
          - x-forwarded-user-family-name
          - x-forwarded-user-given-name
          - x-forwarded-user-mfa
```

The `redirect_state=302` param switches the status code in case of no session from `401` to `302`. This is probably necessary, because on error, Traefik should return the resposne as-is to the user, and a `401` would not auto-redirect. But I have not tested this yet.

## Why is this secure?

The cookies are (by default) `__Host-*` cookies with all the necessary, hardened cookie settings. The session cookie is `same-site: lax` to make routing possible and the additional CSRF check cookie is `same-site: strict`.

To harden these cookies that much, the `/callback` must be injected into the exact same domain / host as the client app. This means you need to find a route that does not overlap. Probably something like `/callback` or `/oidc/callback` should always be unused, when you client app does not support any of these mechanisms in the first place. You could also do something very unlikely overlapping things like `/oidc/rauthy/fwd_auth/callback` or whatever makes sense in your case. This does not matter, only the host, so the browser sets the cookie correctly.

--- 

I am not completely sold on the location of the routes yet, if they should be in `/clients/{id}/`, or maybe something a bit more independent and parse the `client_id` from reqeust params, but any configuration should work. This is probably more about proxy configuration.

The fact that you can use it with any client also makes it possible to either just use a single `forward_auth` client for all your needs, or have multiple ones, which you can independently enable / disable.

I think for testing, this setup should do the trick.

For other proxy configs, the [authentik docs](https://docs.goauthentik.io/docs/add-secure-apps/providers/proxy/server_caddy) are probably a good starting point.

Edit:

Forgot to mention:
In the nginx example config, the `/whoami` route is the private / protected one. I route this back to Rauthy itself, so I can easily see the request headers and make sure everything has been forwarded correctly.

**Comment by sebadob** [comment]
Just found a bug with fresh sessions. It's possible that you can get to the `/callback` endpoint with a session that's still in `SessionState::Init` and you would be rejected.

I need to fix that and push a new testing image. Until then, it should work when you already have a session on Rauthy beforehand.

**Comment by sebadob** [comment]
`ghcr.io/sebadob/rauthy:0.30.3-20250619-fwd-auth-1` has some things fixed.

**Comment by sebadob** [comment]
This is working nicely. Inside K8s, I had no issues with Traefik and this config works perfectly fine. Here as well, if `auth_headers.enable = false`, you could even remove the whole `authResponseHeaders` block. I am using Rauthy's `/auth/v1/whoami` for debugging again. I also added a new config var to include all those debugging headers in release mode.

```toml
[access]
# If set to `true`, the `/auth/v1/whoami` endpoint will return all
# request headers. Only the `Cookie` and Rauthys internal CSRF headers
# will be hidden. Since this has the potential to leak sensitive
# information, depending on you networking, this is disabled by default.
#
# default: false
# overwritten by: WHOAMI_HEADERS
whoami_headers = true
```

Traefik `IngressRoute` inside K8s:

```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fwd-auth
spec:
  forwardAuth:
    # the id for the properly configured client is `fwd-auth-test` in this case
    address: http://rauthy.rauthy-dev.svc.cluster.local:8080/auth/v1/clients/fwd-auth-test/forward_auth?redirect_state=302
    authResponseHeaders:
      - x-forwarded-user
      - x-forwarded-user-roles
      - x-forwarded-user-groups
      - x-forwarded-user-email
      - x-forwarded-user-email-verified
      - x-forwarded-user-family-name
      - x-forwarded-user-given-name
      - x-forwarded-user-mfa
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fwd-auth-callback
spec:
  replacePath:
    # the id for the properly configured client is `fwd-auth-test` in this case
    path: /auth/v1/clients/fwd-auth-test/forward_auth/callback
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: whoami-replace
spec:
  replacePath:
    path: /auth/v1/whoami
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rauthy-https
  namespace: rauthy-dev
spec:
  entryPoints:
    - websecure
  tls:
    secretName: iam.sebadob.dev-tls
  routes:
    - match: Host(`iam.sebadob.dev`)
      kind: Rule
      services:
        - name: rauthy
          port: 8080
    - match: Host(`iam.sebadob.dev`) && Path(`/whoami`)
      kind: Rule
      middlewares:
        # CAUTION: very important to have the fwd-auth BEFORE any path rewriting.
        # You can set a fixed redirect URI when you overwrite `X-Forwarded-URI`.
        - name: fwd-auth
        - name: whoami-replace
      services:
        - name: rauthy
          port: 8080
    - match: Host(`iam.sebadob.dev`) && Path(`/callback`)
      kind: Rule
      middlewares:
        - name: fwd-auth-callback
      services:
        - name: rauthy
          port: 8080
```

--- 

I am pretty sure Caddy as well will be just fine, so I can clean up a PR a bit and then merge it.
