### ISSUE TITLE
NetBird logout failed

### ISSUE THREAD

**Issue by pearlau** [sebadob/rauthy#1060]
Everything went smoothly when I logged into NetBird using Rauthy.
During logout, I experienced the following issue:
```json
{
  "timestamp": 1750605211,
  "error": "BadRequest",
  "message": "Invalid post_logout_redirect_uri"
}
```

### Configuration for NetBird in Rauthy's clients section:
  
**id**
`netbird`
  
**Client Configuration**
- [x] Enabled
- [x] Confidential
  
**Authentication Flows**
- [x] authorization_code
- [x] refresh_token
  
**PKCE**
- [x] S256
  
**Origin**
- Allowed Origins : **https://<netbird.domain>**
- Redirect URIs : **https://<netbird.domain>**  **https://<netbird.domain>/*** **http://localhost:53000**
- Post Logout Redirect URIs : **https://<netbird.domain>**
  
**Scopes**
- email, openid, profile, groups
  
**Tokens**
- Access Token Algorithm : **RS256**
- ID Token Algorithm : **RS256**

### Sections to modify in NetBird's `management.json` configuration file.
```json
{
    "HttpConfig": {
        "LetsEncryptDomain": "",
        "CertFile": "",
        "CertKey": "",
        "AuthAudience": "netbird",
        "AuthIssuer": "https://<Your rauthy domain>/auth/v1",
        "AuthUserIDClaim": "",
        "AuthKeysLocation": "https://<Your rauthy domain>/auth/v1/oidc/certs",
        "OIDCConfigEndpoint": "https://<Your rauthy domain>/.well-known/openid-configuration",
        "IdpSignKeyRefreshEnabled": false,
        "ExtraAuthAudience": ""
    },
    "IdpManagerConfig": {
        "ManagerType": "",
        "ClientConfig": {
            "Issuer": "https://<Your rauthy domain>/auth/v1",
            "TokenEndpoint": "https://<Your rauthy domain>/auth/v1/oidc/token",
            "ClientID": "netbird",
            "ClientSecret": "<client secret>",
            "GrantType": "client_credentials"
        },
        "Auth0ClientCredentials": null,
        "AzureClientCredentials": null,
        "KeycloakClientCredentials": null,
        "ZitadelClientCredentials": null
    },
    "DeviceAuthorizationFlow": {
        "Provider": "hosted",
        "ProviderConfig": {
            "ClientID": "netbird",
            "ClientSecret": "<client secret>",
            "Domain": "<Your rauthy domain>",
            "Audience": "netbird",
            "TokenEndpoint": "https://<Your rauthy domain>/auth/v1/oidc/token",
            "DeviceAuthEndpoint": "https://<Your rauthy domain>/auth/v1/oidc/device",
            "AuthorizationEndpoint": "",
            "Scope": "openid",
            "UseIDToken": false,
            "RedirectURLs": null,
            "DisablePromptLogin": false,
            "LoginFlag": 0
        }
    },
    "PKCEAuthorizationFlow": {
        "ProviderConfig": {
            "ClientID": "netbird",
            "ClientSecret": "<client secret>",
            "Domain": "",
            "Audience": "netbird",
            "TokenEndpoint": "https://<Your rauthy domain>/auth/v1/oidc/token",
            "DeviceAuthEndpoint": "",
            "AuthorizationEndpoint": "https://<Your rauthy domain>/auth/v1/oidc/authorize",
            "Scope": "openid profile email groups",
            "UseIDToken": false,
            "RedirectURLs": [
                "http://localhost:53000"
            ],
            "DisablePromptLogin": true,
            "LoginFlag": 1
        }
    }
}
```
### Netbird docker-compose
```yaml
services:
  # UI dashboard
  dashboard:
    image: netbirdio/dashboard:latest
    restart: unless-stopped
    ports:
      - 8011:80
      # - 443:443
    environment:
      # Endpoints
      - NETBIRD_MGMT_API_ENDPOINT=https://<netbird.domain>
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=https://<netbird.domain>
      # OIDC
      - AUTH_AUDIENCE=netbird
      - AUTH_CLIENT_ID=netbird
      - AUTH_CLIENT_SECRET=<client secret>
      - AUTH_AUTHORITY=https://<Your rauthy domain>/auth/v1
      - USE_AUTH0=false
      - AUTH_SUPPORTED_SCOPES=openid profile email groups
      - AUTH_REDIRECT_URI=
      - AUTH_SILENT_REDIRECT_URI=
      - NETBIRD_TOKEN_SOURCE=idToken
```
**There are no error logs in the Rauthy Docker logs. I hope this helps resolve the logout issue. Thanks!**
