### ISSUE TITLE
overly restrictive regex

### ISSUE THREAD

**Issue by nicholascioli** [sebadob/rauthy#636]
Hello,

I've been using Rauthy these past few days to add SSO to OwnCloud and I've run into an issue with the regex rules for some of the fields.

By default (and as [per their docs](https://doc.owncloud.com/ocis/next/deployment/services/s-list/proxy.html#automatic-role-assignments)), OwnCloud expects the following mappings from OIDC user roles to OwnCloud user types:
```
role_assignment:
    driver: oidc
    oidc_role_mapper:
        role_claim: ocisRoles
        role_mapping:
            - role_name: admin
              claim_value: myAdminRole
            - role_name: spaceadmin
              claim_value: mySpaceAdminRole
            - role_name: user
              claim_value: myUserRole
            - role_name: guest
              claim_value: myGuestRole
```

But the default rules around valid roles disallows capital letters, [as it is defined](https://github.com/sebadob/rauthy/blob/091b36284f9791e4ebd83c8a1bb1537edfbc46ec/frontend/src/utils/constants.js#L44C29-L44C51) as `^[a-z0-9\-_/:*]{2,64}$`. Since OwnCloud lets you override these defaults, I was able to move ahead without issue.

The main issue is that when setting up the client credentials for OwnCloud's Android app, which has a client ID of `e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD` (shown [here](https://doc.owncloud.com/ocis/next/deployment/services/s-list/idp.html#yaml-example)), the [regex for valid client IDs](https://github.com/sebadob/rauthy/blob/091b36284f9791e4ebd83c8a1bb1537edfbc46ec/frontend/src/utils/constants.js#L37) also disallows capital letters.

Is this a case of OwnCloud not following the spec or should I make a PR to update these regexs?

Thanks again for Rauthy; it's been a joy to use in comparison to heavier IdPs.
