### ISSUE TITLE
Better Testing / Local Evaluation with MailCrab

### ISSUE THREAD

**Issue by Ganipotes** [sebadob/rauthy#959]
**Is your feature request related to a problem? Please describe.**
The [Testing / Local Evaluation](https://sebadob.github.io/rauthy/getting_started/docker.html#testing--local-evaluation) is incomplete, it's missing the mail testing with something like MailCrab.

**Describe the solution you'd like**
Have a docker-compose.yml that will launch both MailCrab and Rauthy.

Something like that:

```
services:
  rauthy:
    image: ghcr.io/sebadob/rauthy:latest
    environment:
      - LOCAL_TEST=true
      - SMTP_URL=mailcrab
      - SMTP_PORT=1025
      - SMTP_DANGER_INSECURE=true
      - SMTP_DANGER_INSECURE_PORT=1025
      - SMTP_FROM=rauthy@test.local
      - LOG_LEVEL=debug
      - BACKCHANNEL_DANGER_ALLOW_INSECURE=false
    ports:
      - "8080:8080"
    depends_on:
      - mailcrab
    networks:
      - testnet

  mailcrab:
    image: marlonb/mailcrab:latest
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - testnet

networks:
  testnet:
    driver: bridge 
```

**Describe alternatives you've considered**
Have also a Podman + Quadlet for linux with systemd?
